export const colors = {
  transparent: '#00000000',
  white: '#fff',
  black: '#000',
  lightGray: '#fafbfc',
  lightGrayBorder: '#e1e4e8',
  lightGrayText: '#586069',
  grayBackground: '#f6f8fa',
  grayBorder: '#b9b9b9',
  primary: '#0265d6',
  dark: '#0366d6',
  light: '#58a5f0',
  primaryRed: '#931332',
  primaryGray: '#666666',
  notEditableField: 'rgba(127, 127, 127, 0.3)',
  searchInputBorder: '#9e9e9e',
  priceInputBorder: '#dcdcdc',
  priceInputPlaceholedText: '#B5B5B5',
  priceInputText: '#333333',

  switchToggleOn: 'rgba(69, 208, 158, 0.5)',
  switchToggleOff: '#ededed',
  switchNotchOn: '#45d09e',
  switchNotchOff: '#e0e0e0',

  modalCover: 'rgba(15, 15, 15, 0.38)',
} as const

export const COLOR_KEYS = {
  transparent: 'transparent',
  white: 'white',
  black: 'black',
  lightGray: 'lightGray',
  lightGrayBorder: 'lightGrayBorder',
  lightGrayText: 'lightGrayText',
  grayBackground: 'grayBackground',
  grayBorder: 'grayBorder',
  primary: 'primary',
  dark: 'dark',
  light: 'light',
  primaryRed: 'primaryRed',
  primaryGray: 'primaryGray',
  notEditableField: 'notEditableField',
  searchInputBorder: 'searchInputBorder',
  priceInputBorder: 'priceInputBorder',
  priceInputPlaceholedText: 'priceInputPlaceholedText',
  priceInputText: 'priceInputText',

  switchToggleOn: 'switchToggleOn',
  switchToggleOff: 'switchToggleOff',
  switchNotchOn: 'switchNotchOn',
  switchNotchOff: 'switchNotchOff',
  modalCover: 'modalCover',
} as const
