export const colors = {
  transparent: '#00000000',
  white: '#fff',
  black: '#000',
  lightGray: '#fafbfc',
  lightGrayBorder: '#e1e4e8',
  lightGrayText: '#586069',
  grayBackground: '#f6f8fa',
  grayBorder: '#b9b9b9',
  primary: '#0265d6',
  dark: '#0366d6',
  light: '#58a5f0',
  primaryRed: '#931332',
  primaryGray: '#666666',
  primaryDarkRed: '#680e24',
  shadowButton: 'rgba(104, 14, 36, 0.25)',
} as const

export const COLOR_KEYS = {
  transparent: 'transparent',
  white: 'white',
  black: 'black',
  lightGray: 'lightGray',
  lightGrayBorder: 'lightGrayBorder',
  lightGrayText: 'lightGrayText',
  grayBackground: 'grayBackground',
  grayBorder: 'grayBorder',
  primary: 'primary',
  dark: 'dark',
  light: 'light',
  primaryRed: 'primaryRed',
  primaryGray: 'primaryGray',
  primaryDarkRed: 'primaryDarkRed',
  shadowButton: 'shadowButton',
} as const
